global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'observe-demo'

rule_files:
  - 'recording.rules.yml'

scrape_configs:
  - job_name: observe
    scheme: https
    scrape_interval: 5s
    static_configs:
      - targets: ['observe-demo:40089']
        labels:
          service: 'observe-1'
      - targets: ['host.docker.internal:4001']
        labels:
          service: 'observe-2'
