global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: '<monitor-name>'

rule_files:
  - 'recording.rules.yml'

scrape_configs:
  - job_name: <job-name>
    static_configs:
      - targets: ['<target>']
