global:
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - prometheus-e83j.onrender.com
- job_name: demo
  static_configs:
  - targets:  
    - prometheus-demo-service.onrender.com
  metric_relabel_configs:
  - action: keep
    source_labels: [__name__]
    regex: '(demo_|http_).*'
- job_name: redirector
  static_configs:
  - targets:
    - ux-research-redirector.onrender.com
remote_write:
- url: https://prometheus-prod-13-prod-us-east-0.grafana.net/api/prom/push
  basic_auth:
    username: 1495985
    password: "glc_eyJvIjoiNjk0NTU5IiwibiI6InJlbW90ZS13cml0ZS1mb3ItZGF0YS10cmFpbHMtc2hvcnQtdG9rZW4iLCJrIjoia0NoaTE3ZGZnOG0wZHo5ME5maDcyYTI1IiwibSI6eyJyIjoicHJvZC11cy1lYXN0LTAifX0="
