global:
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - prometheus-e83j.onrender.com
  metric_relabel_configs:
	- action:keep
	  source_labels:[__name__]
	  regex: '(demo_|http_).*'
- job_name: demo
  static_configs:
  - targets:
    - prometheus-demo-service.onrender.com
- job_name: redirector
  static_configs:
  - targets:
    - ux-research-redirector.onrender.com
