global:
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
- job_name: demo
  static_configs:
  - targets:  
    - prometheus-demo-service.onrender.com
  metric_relabel_configs:
  - action: drop
    source_labels: [__name__]
    regex: 'go_.*'
