global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'observe-demo'

rule_files:
  - 'recording.rules.yml'

scrape_configs:
  - job_name: observe
    scrape_interval: 5s
    static_configs:
      - targets: ['observe-demo:10000']
        labels:
          service: 'observe-1'
