groups:
  - name: avg_tesla_duration
    interval: 5s
    rules:
    - record: job:avg_tesla_duration:summary
      expr: sum by (job)(rate(tesla_request_duration_sum[5m])) / sum by (job)(rate(tesla_request_duration_count[5m]))

  - name: total_tesla_requests
    interval: 5s
    rules:
    - record: job:total_tesla_requests:counter
      expr: round(sum by (job) (increase(tesla_request_duration_count[24h])))
  - name: tesla_query_rate
    interval: 5s
    rules:
    - record: job:tesla_query_rate:avg
      expr: avg(rate(tesla_request_duration_count[20s])) by (job) / 20


