groups:
  - name: events
    interval: 5s
    rules:
      - record: job:events_emitted:total
        expr: sum by (job) (observe_calls_made_total) * 10
  - name: tesla
    interval: 5s
    rules:
      - record: job:avg_tesla_duration:summary
        expr: sum by (job)(rate(tesla_request_duration_sum[5m])) / sum by (job)(rate(tesla_request_duration_count[5m]))
      - record: job:total_tesla_requests:counter
        expr: round(sum by (job) (increase(tesla_request_duration_count[24h])))
      - record: job:tesla_query_rate:avg
        expr: avg(rate(tesla_request_duration_count[25s])) by (job)
      - record: job:tesla_queries:total
        expr: sum by (job)(tesla_request_duration_count)

